CREATE TABLE IF NOT EXISTS configuracion (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    centro TEXT NOT NULL,
    anio INTEGER NOT NULL,
    modo_ejercicio TEXT NOT NULL DEFAULT 'Año',
    fecha_inicio DATE NOT NULL,
    fecha_cierre DATE NOT NULL,
    tipo_cierre TEXT NOT NULL DEFAULT 'vivienda',
    num_residentes INTEGER,
    version TEXT,
    observaciones_613_p TEXT,
    observaciones_613_g TEXT,
    media_cocina_mes TEXT,
    media_cocina_acum TEXT,
    saldo_cc_personales TEXT,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS personas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    apellidos TEXT NOT NULL,
    iniciales TEXT NOT NULL UNIQUE,
    mes_exento_inicio INTEGER,
    mes_exento_fin INTEGER,
    mes_exento2_inicio INTEGER,
    mes_exento2_fin INTEGER,
    importe_vivienda_fijo TEXT,
    orden INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS conceptos (
    codigo TEXT NOT NULL,
    cuenta TEXT NOT NULL,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    naturaleza TEXT NOT NULL,
    orden INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (codigo, cuenta)
);

CREATE TABLE IF NOT EXISTS apuntes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    cuenta TEXT NOT NULL,
    origen TEXT NOT NULL,
    iniciales TEXT,
    concepto_codigo TEXT NOT NULL,
    observaciones TEXT,
    cantidad TEXT NOT NULL,
    es_cierre INTEGER NOT NULL DEFAULT 0,
    par_id INTEGER,
    created_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_apuntes_fecha ON apuntes (fecha);
CREATE INDEX IF NOT EXISTS idx_apuntes_cuenta_concepto ON apuntes (cuenta, concepto_codigo);
CREATE INDEX IF NOT EXISTS idx_apuntes_iniciales ON apuntes (iniciales);

CREATE TABLE IF NOT EXISTS presupuesto_lineas (
    cuenta TEXT NOT NULL,
    concepto_codigo TEXT NOT NULL,
    previsto TEXT NOT NULL DEFAULT '0',
    PRIMARY KEY (cuenta, concepto_codigo)
);

CREATE TABLE IF NOT EXISTS arqueos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta TEXT NOT NULL,
    fecha DATE NOT NULL,
    desglose_json TEXT NOT NULL,
    total_dinero TEXT,
    total_vales TEXT,
    total TEXT
);
